BN:
  NUM_SAMPLES_PRECISE: 1024
  USE_PRECISE_STATS: true
CUDNN:
  BENCHMARK: false
DATA_LOADER:
  NUM_WORKERS: 4
MODEL:
  LAYERS: 3
  NUM_CLASSES: 10
  TYPE: mlpnet
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: true
  WEIGHT_DECAY: 0.0005
OUT_DIR: .
RESNET:
  TRANS_FUN: talklinear_transform
RGRAPH:
  ADD_1x1: 0
  AGG_FUNC: sum
  DIM_FIRST: 512
  DIM_LIST:
  - 512
  GROUP_NUM: 64
  KEEP_GRAPH: true
  MESSAGE_TYPE: ws
  P: 0.128063
  SEED_GRAPH: 4
  SEED_TRAIN_END: 6
  SEED_TRAIN_START: 1
  SPARSITY: 0.128001
  TALK_MODE: dense
  UPPER: true
TEST:
  BATCH_SIZE: 100
  DATASET: cifar10
  SPLIT: test
TRAIN:
  AUTO_MATCH: true
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 500
  DATASET: cifar10
  EVAL_PERIOD: 1
  SPLIT: train
